apiVersion: database.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  name: postgres-default
spec:
  forProvider:
    backendRef:
      name: db
    dbName: postgres
    creationStatements:
      - "CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';"
  providerConfigRef:
    name: example-vault
