apiVersion: database.vault.upbound.io/v1alpha1
kind: SecretBackendConnection
metadata:
  name: postgres
spec:
  forProvider:
    backendRef:
      name: db
    allowedRoles:
      - postgres-default
    postgresql:
      - connectionUrl: postgres://{{username}}:{{password}}@127.0.0.1:5432/postgres
        username: postgres
        passwordSecretRef:
          name: mysecret
          key: password
          namespace: default
  providerConfigRef:
    name: example-vault
