apiVersion: database.vault.upbound.io/v1alpha1
kind: SecretBackendConnection
metadata:
  name: postgres
spec:
  forProvider:
    backend: /db
    allowedRoles:
      - readonly
    postgresql:
      - connectionUrl: postgres://{{username}}:{{password}}@postgres.default.svc.cluster.local:5432/app
        username: app
        passwordSecretRef:
          name: mysecret
          key: password
          namespace: default
  providerConfigRef:
    name: default
